### ISSUE TITLE
BUG: RTD shows up when searching for "mne rawarray"

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-project-template#6]
This link:

https://mne-foobar.readthedocs.io/en/latest/auto_examples/plot_mne_objects_from_arrays.html

is problematic because searching "mne rawarray" this is in the first few results.

I propose we kill the RTD site for this repo.

Also this repo is pretty out of date and nowadays I just tell people to build a skeleton off of one of the existing projects (MNE-BIDS, MNE-Python, or MNE-Realtime) because these have CIs that are kept up to date and working. I doubt anyone wants to maintain those things here, so I am inclined just to delete this repository entirely because I don't think it helps much.

**Comment by larsoner** [comment]
cc @agramfort

**Comment by agramfort** [comment]
+1 to kill this website. I did not even remember it existed.

we should have only https://github.com/mne-tools/mne-project-template
and https://mne.tools/mne-project-template/

but I don't have admin rights on this website.

maybe @massich does?

**Comment by massich** [comment]
+1 to kill it.
Template projects seem to age super bad unless you bootstrap many projects and port things back often.

I've deleted the project in hope that that would tare the website down (but it seems to still be up)  
![image](https://user-images.githubusercontent.com/7044835/126883206-5bc36d35-689c-4fde-81da-3ada438e953d.png)

**Comment by agramfort** [comment]
it's gone now

thx @massich !

>
